--!strict
-- Registre des 60 ?v?nements de base + g?n?ration automatique de variantes (180 total)

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Config = require(ReplicatedStorage.Shared.Config)
local RNG = require(ReplicatedStorage.Shared.RNG)

local EventRegistry = {}

export type EventSpec = {
	id: string,
	name: string,
	minNight: number,
	difficultyTier: number,
	dbPulse: number?,
	dbTickPerSec: number?,
	resolveTimeSec: number?,
	failDbBurst: number?,
	maxInstances: number,
	prefabType: string,
	interactTag: string?,
	resolveSteps: number?,
	description: string,
}

-- 60 ?v?nements de base
local BaseEvents: { EventSpec } = {
	{
		id = "tempete_volets",
		name = "Temp?te - Volets battants",
		minNight = 1,
		difficultyTier = 1,
		dbPulse = 12,
		resolveTimeSec = 8,
		failDbBurst = 10,
		maxInstances = 2,
		prefabType = "Shutter",
		interactTag = "ShutterLatch",
		resolveSteps = 1,
		description = "Fermer les volets pour emp?cher qu'ils battent",
	},
	{
		id = "voisin_doorbell",
		name = "Voisin insistant (sonnette)",
		minNight = 1,
		difficultyTier = 2,
		dbTickPerSec = 3,
		resolveTimeSec = 10,
		failDbBurst = 12,
		maxInstances = 1,
		prefabType = "Doorbell",
		interactTag = "DoorbellButton",
		resolveSteps = 1,
		description = "D?sactiver la sonnette rapidement",
	},
	{
		id = "bebe_crib",
		name = "B?b? qui pleure",
		minNight = 1,
		difficultyTier = 2,
		dbTickPerSec = 4,
		resolveTimeSec = 12,
		failDbBurst = 15,
		maxInstances = 1,
		prefabType = "BabyCrib",
		interactTag = "CribRock",
		resolveSteps = 2,
		description = "Bercer le b?b? pour le calmer",
	},
	{
		id = "porte_ouverte",
		name = "Porte claquant au vent",
		minNight = 1,
		difficultyTier = 1,
		dbPulse = 10,
		resolveTimeSec = 6,
		failDbBurst = 8,
		maxInstances = 3,
		prefabType = "SlamDoor",
		interactTag = "DoorClose",
		resolveSteps = 1,
		description = "Fermer la porte",
	},
	{
		id = "chat_vase",
		name = "Chat qui renverse un vase",
		minNight = 1,
		difficultyTier = 1,
		dbPulse = 15,
		resolveTimeSec = 10,
		failDbBurst = 8,
		maxInstances = 2,
		prefabType = "CatVase",
		interactTag = "VaseSecure",
		resolveSteps = 1,
		description = "S?curiser le vase avant qu'il tombe",
	},
	{
		id = "generateur_bip",
		name = "G?n?rateur qui bipe",
		minNight = 2,
		difficultyTier = 2,
		dbTickPerSec = 2.5,
		resolveTimeSec = 15,
		failDbBurst = 10,
		maxInstances = 1,
		prefabType = "Generator",
		interactTag = "GeneratorSwitch",
		resolveSteps = 2,
		description = "?teindre le g?n?rateur",
	},
	{
		id = "pendule_dechainee",
		name = "Pendule d?cha?n?e",
		minNight = 1,
		difficultyTier = 2,
		dbTickPerSec = 3.5,
		resolveTimeSec = 12,
		failDbBurst = 12,
		maxInstances = 2,
		prefabType = "Pendulum",
		interactTag = "PendulumStop",
		resolveSteps = 1,
		description = "Arr?ter la pendule",
	},
	{
		id = "pluie_toiture",
		name = "Fuite de toiture (pluie)",
		minNight = 2,
		difficultyTier = 3,
		dbTickPerSec = 2,
		resolveTimeSec = 20,
		failDbBurst = 14,
		maxInstances = 2,
		prefabType = "RoofLeak",
		interactTag = "LeakPatch",
		resolveSteps = 3,
		description = "Colmater la fuite",
	},
	{
		id = "fenetre_malfermee",
		name = "Fen?tre mal ferm?e",
		minNight = 1,
		difficultyTier = 1,
		dbPulse = 8,
		resolveTimeSec = 7,
		failDbBurst = 9,
		maxInstances = 3,
		prefabType = "Window",
		interactTag = "WindowLatch",
		resolveSteps = 1,
		description = "Fermer la fen?tre correctement",
	},
	{
		id = "rat_cuisine",
		name = "Rat dans la cuisine",
		minNight = 1,
		difficultyTier = 2,
		dbTickPerSec = 2.8,
		resolveTimeSec = 15,
		failDbBurst = 11,
		maxInstances = 2,
		prefabType = "Rat",
		interactTag = "RatTrap",
		resolveSteps = 2,
		description = "Poser un pi?ge ? rat",
	},
	{
		id = "chaudiere_siffle",
		name = "Chaudi?re qui siffle",
		minNight = 2,
		difficultyTier = 3,
		dbTickPerSec = 3.2,
		resolveTimeSec = 18,
		failDbBurst = 13,
		maxInstances = 1,
		prefabType = "Boiler",
		interactTag = "BoilerValve",
		resolveSteps = 2,
		description = "Ajuster la valve de la chaudi?re",
	},
	{
		id = "porte_grince",
		name = "Porte qui grince",
		minNight = 1,
		difficultyTier = 1,
		dbPulse = 9,
		resolveTimeSec = 8,
		failDbBurst = 8,
		maxInstances = 3,
		prefabType = "CreakDoor",
		interactTag = "DoorOil",
		resolveSteps = 1,
		description = "Huiler les gonds de la porte",
	},
	{
		id = "rideaux_battent",
		name = "Rideaux qui battent",
		minNight = 1,
		difficultyTier = 1,
		dbPulse = 7,
		resolveTimeSec = 6,
		failDbBurst = 7,
		maxInstances = 3,
		prefabType = "Curtains",
		interactTag = "CurtainTie",
		resolveSteps = 1,
		description = "Attacher les rideaux",
	},
	{
		id = "boite_a_musique",
		name = "Bo?te ? musique d?clench?e",
		minNight = 2,
		difficultyTier = 3,
		dbTickPerSec = 4,
		resolveTimeSec = 10,
		failDbBurst = 14,
		maxInstances = 1,
		prefabType = "MusicBox",
		interactTag = "MusicBoxClose",
		resolveSteps = 1,
		description = "Fermer la bo?te ? musique",
	},
	{
		id = "livre_tombe",
		name = "Pile de livres qui tombe",
		minNight = 1,
		difficultyTier = 1,
		dbPulse = 14,
		resolveTimeSec = 9,
		failDbBurst = 9,
		maxInstances = 2,
		prefabType = "BookPile",
		interactTag = "BookRestack",
		resolveSteps = 1,
		description = "Stabiliser la pile de livres",
	},
	{
		id = "tuyau_heurte",
		name = "Tuyau qui heurte le mur",
		minNight = 2,
		difficultyTier = 2,
		dbTickPerSec = 2.5,
		resolveTimeSec = 14,
		failDbBurst = 11,
		maxInstances = 2,
		prefabType = "Pipe",
		interactTag = "PipeSecure",
		resolveSteps = 2,
		description = "S?curiser le tuyau",
	},
	{
		id = "horloge_coucou",
		name = "Horloge coucou",
		minNight = 1,
		difficultyTier = 2,
		dbPulse = 16,
		resolveTimeSec = 8,
		failDbBurst = 12,
		maxInstances = 2,
		prefabType = "CuckooClock",
		interactTag = "ClockDisable",
		resolveSteps = 1,
		description = "D?sactiver le coucou",
	},
	{
		id = "chien_voisin",
		name = "Chien du voisin qui aboie",
		minNight = 2,
		difficultyTier = 3,
		dbTickPerSec = 3.5,
		resolveTimeSec = 20,
		failDbBurst = 15,
		maxInstances = 1,
		prefabType = "Dog",
		interactTag = "DogCalm",
		resolveSteps = 3,
		description = "Calmer le chien",
	},
	{
		id = "telephone_fixe",
		name = "T?l?phone fixe qui sonne",
		minNight = 1,
		difficultyTier = 2,
		dbTickPerSec = 4.5,
		resolveTimeSec = 7,
		failDbBurst = 13,
		maxInstances = 1,
		prefabType = "Phone",
		interactTag = "PhonePickup",
		resolveSteps = 1,
		description = "D?crocher le t?l?phone",
	},
	{
		id = "radio_parasites",
		name = "Radio avec parasites",
		minNight = 2,
		difficultyTier = 2,
		dbTickPerSec = 3,
		resolveTimeSec = 12,
		failDbBurst = 11,
		maxInstances = 1,
		prefabType = "Radio",
		interactTag = "RadioOff",
		resolveSteps = 1,
		description = "?teindre la radio",
	},
	{
		id = "ventouse_fenetre",
		name = "Ventouse sur fen?tre",
		minNight = 1,
		difficultyTier = 1,
		dbPulse = 11,
		resolveTimeSec = 10,
		failDbBurst = 9,
		maxInstances = 2,
		prefabType = "Suction",
		interactTag = "SuctionRemove",
		resolveSteps = 1,
		description = "Retirer la ventouse",
	},
	{
		id = "armoire_porte_claque",
		name = "Porte d'armoire qui claque",
		minNight = 1,
		difficultyTier = 1,
		dbPulse = 10,
		resolveTimeSec = 7,
		failDbBurst = 8,
		maxInstances = 3,
		prefabType = "CabinetDoor",
		interactTag = "CabinetLatch",
		resolveSteps = 1,
		description = "Fermer l'armoire",
	},
	{
		id = "boite_a_lettre",
		name = "Bo?te aux lettres qui claque",
		minNight = 1,
		difficultyTier = 1,
		dbPulse = 9,
		resolveTimeSec = 8,
		failDbBurst = 8,
		maxInstances = 1,
		prefabType = "Mailbox",
		interactTag = "MailboxSecure",
		resolveSteps = 1,
		description = "S?curiser la bo?te aux lettres",
	},
	{
		id = "escalier_craque",
		name = "Marche d'escalier qui craque",
		minNight = 2,
		difficultyTier = 2,
		dbTickPerSec = 2,
		resolveTimeSec = 16,
		failDbBurst = 10,
		maxInstances = 2,
		prefabType = "Stair",
		interactTag = "StairFix",
		resolveSteps = 2,
		description = "R?parer la marche",
	},
	{
		id = "plantes_chutent",
		name = "Plantes en pot qui tombent",
		minNight = 1,
		difficultyTier = 1,
		dbPulse = 13,
		resolveTimeSec = 9,
		failDbBurst = 9,
		maxInstances = 2,
		prefabType = "PlantPot",
		interactTag = "PlantSecure",
		resolveSteps = 1,
		description = "Stabiliser les plantes",
	},
	{
		id = "thermometre_vitre",
		name = "Thermom?tre qui tape la vitre",
		minNight = 1,
		difficultyTier = 1,
		dbTickPerSec = 1.8,
		resolveTimeSec = 10,
		failDbBurst = 8,
		maxInstances = 2,
		prefabType = "Thermometer",
		interactTag = "ThermometerMove",
		resolveSteps = 1,
		description = "?loigner le thermom?tre",
	},
	{
		id = "tableau_pend",
		name = "Tableau qui pend de travers",
		minNight = 1,
		difficultyTier = 1,
		dbPulse = 8,
		resolveTimeSec = 7,
		failDbBurst = 7,
		maxInstances = 3,
		prefabType = "Painting",
		interactTag = "PaintingStraighten",
		resolveSteps = 1,
		description = "Redresser le tableau",
	},
	{
		id = "souris_moulures",
		name = "Souris dans les moulures",
		minNight = 2,
		difficultyTier = 2,
		dbTickPerSec = 2.2,
		resolveTimeSec = 15,
		failDbBurst = 10,
		maxInstances = 2,
		prefabType = "Mouse",
		interactTag = "MouseTrap",
		resolveSteps = 2,
		description = "Poser un pi?ge ? souris",
	},
	{
		id = "fuite_air_porte",
		name = "Fuite d'air sous la porte",
		minNight = 2,
		difficultyTier = 2,
		dbTickPerSec = 1.5,
		resolveTimeSec = 14,
		failDbBurst = 9,
		maxInstances = 2,
		prefabType = "DoorDraft",
		interactTag = "DraftBlock",
		resolveSteps = 2,
		description = "Bloquer la fuite d'air",
	},
	{
		id = "vaisselle_pile",
		name = "Pile de vaisselle instable",
		minNight = 1,
		difficultyTier = 2,
		dbPulse = 15,
		resolveTimeSec = 10,
		failDbBurst = 12,
		maxInstances = 2,
		prefabType = "Dishes",
		interactTag = "DishesStabilize",
		resolveSteps = 1,
		description = "Stabiliser la vaisselle",
	},
	{
		id = "lampe_gresille",
		name = "Lampe qui gr?sille",
		minNight = 2,
		difficultyTier = 2,
		dbTickPerSec = 2.5,
		resolveTimeSec = 12,
		failDbBurst = 10,
		maxInstances = 2,
		prefabType = "Lamp",
		interactTag = "LampFix",
		resolveSteps = 2,
		description = "R?parer la lampe",
	},
	{
		id = "tiroir_couine",
		name = "Tiroir qui couine",
		minNight = 1,
		difficultyTier = 1,
		dbPulse = 9,
		resolveTimeSec = 8,
		failDbBurst = 8,
		maxInstances = 3,
		prefabType = "Drawer",
		interactTag = "DrawerOil",
		resolveSteps = 1,
		description = "Huiler le tiroir",
	},
	{
		id = "toit_ardoise",
		name = "Ardoise de toit qui glisse",
		minNight = 3,
		difficultyTier = 4,
		dbTickPerSec = 3,
		resolveTimeSec = 22,
		failDbBurst = 16,
		maxInstances = 1,
		prefabType = "RoofTile",
		interactTag = "TileSecure",
		resolveSteps = 3,
		description = "S?curiser l'ardoise",
	},
	{
		id = "rampe_escalier",
		name = "Rampe d'escalier qui bouge",
		minNight = 2,
		difficultyTier = 2,
		dbTickPerSec = 2,
		resolveTimeSec = 14,
		failDbBurst = 10,
		maxInstances = 1,
		prefabType = "Handrail",
		interactTag = "HandrailTighten",
		resolveSteps = 2,
		description = "Resserrer la rampe",
	},
	{
		id = "aquarium_bulles",
		name = "Aquarium avec bulles bruyantes",
		minNight = 2,
		difficultyTier = 2,
		dbTickPerSec = 2.8,
		resolveTimeSec = 12,
		failDbBurst = 11,
		maxInstances = 1,
		prefabType = "Aquarium",
		interactTag = "AquariumAdjust",
		resolveSteps = 1,
		description = "Ajuster l'aquarium",
	},
	{
		id = "parquet_bossu",
		name = "Parquet bossu qui craque",
		minNight = 2,
		difficultyTier = 3,
		dbTickPerSec = 2.2,
		resolveTimeSec = 18,
		failDbBurst = 12,
		maxInstances = 2,
		prefabType = "FloorBoard",
		interactTag = "FloorFix",
		resolveSteps = 3,
		description = "R?parer le parquet",
	},
	{
		id = "pendule_reverse",
		name = "Pendule ? l'envers",
		minNight = 3,
		difficultyTier = 3,
		dbTickPerSec = 3.5,
		resolveTimeSec = 15,
		failDbBurst = 13,
		maxInstances = 1,
		prefabType = "ReversePendulum",
		interactTag = "PendulumFlip",
		resolveSteps = 2,
		description = "Retourner la pendule",
	},
	{
		id = "rideau_douche",
		name = "Rideau de douche qui bouge",
		minNight = 1,
		difficultyTier = 1,
		dbPulse = 7,
		resolveTimeSec = 7,
		failDbBurst = 7,
		maxInstances = 2,
		prefabType = "ShowerCurtain",
		interactTag = "CurtainSecure",
		resolveSteps = 1,
		description = "S?curiser le rideau",
	},
	{
		id = "ventilateur_equilibre",
		name = "Ventilateur d?s?quilibr?",
		minNight = 2,
		difficultyTier = 3,
		dbTickPerSec = 3.2,
		resolveTimeSec = 16,
		failDbBurst = 13,
		maxInstances = 1,
		prefabType = "Fan",
		interactTag = "FanBalance",
		resolveSteps = 2,
		description = "?quilibrer le ventilateur",
	},
	{
		id = "frigo_bruit",
		name = "Frigo qui fait du bruit",
		minNight = 2,
		difficultyTier = 2,
		dbTickPerSec = 2.5,
		resolveTimeSec = 14,
		failDbBurst = 11,
		maxInstances = 1,
		prefabType = "Fridge",
		interactTag = "FridgeAdjust",
		resolveSteps = 2,
		description = "Ajuster le frigo",
	},
	{
		id = "coffre_charniere",
		name = "Coffre avec charni?re rouill?e",
		minNight = 2,
		difficultyTier = 2,
		dbPulse = 12,
		resolveTimeSec = 10,
		failDbBurst = 11,
		maxInstances = 2,
		prefabType = "Chest",
		interactTag = "ChestOil",
		resolveSteps = 1,
		description = "Huiler le coffre",
	},
	{
		id = "jardin_eolienne",
		name = "?olienne de jardin",
		minNight = 2,
		difficultyTier = 2,
		dbTickPerSec = 2.8,
		resolveTimeSec = 13,
		failDbBurst = 11,
		maxInstances = 1,
		prefabType = "Windmill",
		interactTag = "WindmillStop",
		resolveSteps = 1,
		description = "Arr?ter l'?olienne",
	},
	{
		id = "porte_ferme_porte",
		name = "Ferme-porte cass?",
		minNight = 1,
		difficultyTier = 2,
		dbPulse = 11,
		resolveTimeSec = 9,
		failDbBurst = 10,
		maxInstances = 2,
		prefabType = "DoorCloser",
		interactTag = "CloserFix",
		resolveSteps = 1,
		description = "R?parer le ferme-porte",
	},
	{
		id = "bois_cheminee",
		name = "Bois qui craque dans la chemin?e",
		minNight = 2,
		difficultyTier = 3,
		dbTickPerSec = 2.5,
		resolveTimeSec = 16,
		failDbBurst = 12,
		maxInstances = 1,
		prefabType = "Fireplace",
		interactTag = "FireplaceAdjust",
		resolveSteps = 2,
		description = "Ajuster le bois",
	},
	{
		id = "tasse_vibration",
		name = "Tasse qui vibre sur la table",
		minNight = 1,
		difficultyTier = 1,
		dbTickPerSec = 1.5,
		resolveTimeSec = 8,
		failDbBurst = 7,
		maxInstances = 3,
		prefabType = "Cup",
		interactTag = "CupStabilize",
		resolveSteps = 1,
		description = "Stabiliser la tasse",
	},
	{
		id = "chaise_couine",
		name = "Chaise qui couine",
		minNight = 1,
		difficultyTier = 1,
		dbPulse = 8,
		resolveTimeSec = 8,
		failDbBurst = 8,
		maxInstances = 3,
		prefabType = "Chair",
		interactTag = "ChairOil",
		resolveSteps = 1,
		description = "Huiler la chaise",
	},
	{
		id = "piano_touche_collee",
		name = "Touche de piano coll?e",
		minNight = 3,
		difficultyTier = 4,
		dbTickPerSec = 4,
		resolveTimeSec = 18,
		failDbBurst = 15,
		maxInstances = 1,
		prefabType = "Piano",
		interactTag = "PianoFix",
		resolveSteps = 3,
		description = "R?parer la touche",
	},
	{
		id = "coffret_fusibles",
		name = "Coffret de fusibles qui gr?sille",
		minNight = 3,
		difficultyTier = 4,
		dbTickPerSec = 3.5,
		resolveTimeSec = 20,
		failDbBurst = 14,
		maxInstances = 1,
		prefabType = "FuseBox",
		interactTag = "FuseReplace",
		resolveSteps = 3,
		description = "Remplacer le fusible",
	},
	{
		id = "moulin_cafe",
		name = "Moulin ? caf? automatique",
		minNight = 2,
		difficultyTier = 2,
		dbTickPerSec = 3.8,
		resolveTimeSec = 10,
		failDbBurst = 12,
		maxInstances = 1,
		prefabType = "CoffeeGrinder",
		interactTag = "GrinderOff",
		resolveSteps = 1,
		description = "?teindre le moulin",
	},
	{
		id = "rideau_metal_anneaux",
		name = "Rideau m?tal avec anneaux",
		minNight = 1,
		difficultyTier = 2,
		dbPulse = 11,
		resolveTimeSec = 9,
		failDbBurst = 10,
		maxInstances = 2,
		prefabType = "MetalCurtain",
		interactTag = "CurtainTie",
		resolveSteps = 1,
		description = "Attacher le rideau",
	},
	{
		id = "serrure_siffle",
		name = "Serrure qui siffle",
		minNight = 2,
		difficultyTier = 2,
		dbTickPerSec = 2,
		resolveTimeSec = 12,
		failDbBurst = 10,
		maxInstances = 2,
		prefabType = "Lock",
		interactTag = "LockOil",
		resolveSteps = 2,
		description = "Huiler la serrure",
	},
	{
		id = "boite_jouets_ressort",
		name = "Bo?te ? jouets ? ressort",
		minNight = 2,
		difficultyTier = 3,
		dbPulse = 14,
		resolveTimeSec = 11,
		failDbBurst = 13,
		maxInstances = 1,
		prefabType = "ToyBox",
		interactTag = "ToyBoxClose",
		resolveSteps = 2,
		description = "Fermer la bo?te ? jouets",
	},
	{
		id = "carillon_porte",
		name = "Carillon de porte",
		minNight = 1,
		difficultyTier = 2,
		dbTickPerSec = 3,
		resolveTimeSec = 10,
		failDbBurst = 11,
		maxInstances = 1,
		prefabType = "DoorChime",
		interactTag = "ChimeRemove",
		resolveSteps = 1,
		description = "Retirer le carillon",
	},
	{
		id = "plancher_cave_bulle",
		name = "Plancher de cave avec bulles d'air",
		minNight = 3,
		difficultyTier = 4,
		dbTickPerSec = 2.5,
		resolveTimeSec = 22,
		failDbBurst = 14,
		maxInstances = 1,
		prefabType = "BasementFloor",
		interactTag = "FloorPatch",
		resolveSteps = 3,
		description = "R?parer le plancher",
	},
	{
		id = "gouttiere_goutte",
		name = "Goutti?re qui goutte",
		minNight = 2,
		difficultyTier = 2,
		dbTickPerSec = 2.2,
		resolveTimeSec = 14,
		failDbBurst = 10,
		maxInstances = 2,
		prefabType = "Gutter",
		interactTag = "GutterFix",
		resolveSteps = 2,
		description = "R?parer la goutti?re",
	},
	{
		id = "table_instable",
		name = "Table instable",
		minNight = 1,
		difficultyTier = 1,
		dbTickPerSec = 1.8,
		resolveTimeSec = 10,
		failDbBurst = 8,
		maxInstances = 3,
		prefabType = "Table",
		interactTag = "TableStabilize",
		resolveSteps = 1,
		description = "Stabiliser la table",
	},
	{
		id = "store_latte",
		name = "Store ? lattes qui claque",
		minNight = 1,
		difficultyTier = 1,
		dbPulse = 10,
		resolveTimeSec = 8,
		failDbBurst = 9,
		maxInstances = 2,
		prefabType = "Blinds",
		interactTag = "BlindsSecure",
		resolveSteps = 1,
		description = "S?curiser le store",
	},
	{
		id = "miroir_tape_mur",
		name = "Miroir qui tape le mur",
		minNight = 1,
		difficultyTier = 1,
		dbTickPerSec = 2,
		resolveTimeSec = 9,
		failDbBurst = 8,
		maxInstances = 2,
		prefabType = "Mirror",
		interactTag = "MirrorSecure",
		resolveSteps = 1,
		description = "S?curiser le miroir",
	},
	{
		id = "horloge_murale_marteau",
		name = "Horloge murale (marteau)",
		minNight = 2,
		difficultyTier = 3,
		dbTickPerSec = 3.5,
		resolveTimeSec = 13,
		failDbBurst = 12,
		maxInstances = 1,
		prefabType = "WallClock",
		interactTag = "ClockStop",
		resolveSteps = 2,
		description = "Arr?ter l'horloge",
	},
	{
		id = "couverts_tintement_tiroir",
		name = "Couverts qui tintent dans le tiroir",
		minNight = 1,
		difficultyTier = 1,
		dbTickPerSec = 1.5,
		resolveTimeSec = 8,
		failDbBurst = 7,
		maxInstances = 3,
		prefabType = "Cutlery",
		interactTag = "CutleryArrange",
		resolveSteps = 1,
		description = "Arranger les couverts",
	},
}

-- G?n?re les variantes _Hard et _Chain pour atteindre 180 ?v?nements
function EventRegistry.buildAll(): { EventSpec }
	local allEvents = {}

	for _, baseEvent in ipairs(BaseEvents) do
		-- Ajouter l'?v?nement de base
		table.insert(allEvents, baseEvent)

		-- Variante _Hard
		local hardEvent = table.clone(baseEvent)
		hardEvent.id = baseEvent.id .. "_hard"
		hardEvent.name = baseEvent.name .. " (Difficile)"
		if hardEvent.dbPulse then
			hardEvent.dbPulse = math.floor(hardEvent.dbPulse * 1.25)
		end
		if hardEvent.dbTickPerSec then
			hardEvent.dbTickPerSec = hardEvent.dbTickPerSec * 1.25
		end
		if hardEvent.resolveTimeSec then
			hardEvent.resolveTimeSec = math.floor(hardEvent.resolveTimeSec * 0.8)
		end
		if hardEvent.resolveSteps then
			hardEvent.resolveSteps = hardEvent.resolveSteps + 1
		end
		if hardEvent.failDbBurst then
			hardEvent.failDbBurst = math.floor(hardEvent.failDbBurst * 1.25)
		end
		hardEvent.difficultyTier = math.min(5, hardEvent.difficultyTier + 1)
		table.insert(allEvents, hardEvent)

		-- Variante _Chain
		local chainEvent = table.clone(baseEvent)
		chainEvent.id = baseEvent.id .. "_chain"
		chainEvent.name = baseEvent.name .. " (Encha?n?)"
		-- Convertir dbTickPerSec en pulses jitter
		if chainEvent.dbTickPerSec then
			chainEvent.dbPulse = math.floor(chainEvent.dbTickPerSec * (chainEvent.resolveTimeSec or 10) * 0.6)
			chainEvent.dbTickPerSec = nil
		end
		if chainEvent.dbPulse then
			-- Ajouter du jitter
			local jitter = math.random(10, 25) / 100
			chainEvent.dbPulse = math.floor(chainEvent.dbPulse * (1 + jitter))
		end
		if chainEvent.resolveSteps then
			chainEvent.resolveSteps = chainEvent.resolveSteps * 2
		end
		chainEvent.description = chainEvent.description .. " (deux sous-objectifs)"
		table.insert(allEvents, chainEvent)
	end

	return allEvents
end

-- R?cup?re les ?v?nements ?ligibles pour une nuit donn?e
function EventRegistry.getForNight(night: number, weightsByTier: { [number]: number }): { EventSpec }
	local allEvents = EventRegistry.buildAll()
	local eligible = {}

	for _, event in ipairs(allEvents) do
		if event.minNight <= night then
			table.insert(eligible, event)
		end
	end

	return eligible
end

-- S?lectionne des ?v?nements pond?r?s par tier
function EventRegistry.selectWeighted(
	eligible: { EventSpec },
	count: number,
	weightsByTier: { [number]: number }
): { EventSpec }
	local weights = {}
	for _, event in ipairs(eligible) do
		local weight = weightsByTier[event.difficultyTier] or 1
		table.insert(weights, weight)
	end

	local selected = {}
	local pool = table.clone(eligible)
	local poolWeights = table.clone(weights)

	for i = 1, math.min(count, #pool) do
		local item = RNG.weightedChoice(pool, poolWeights)
		if item then
			table.insert(selected, item)
			-- Retirer de la pool pour ?viter les duplicatas
			local index = table.find(pool, item)
			if index then
				table.remove(pool, index)
				table.remove(poolWeights, index)
			end
		end
	end

	return selected
end

EventRegistry.BaseEvents = BaseEvents

return EventRegistry
